app:
  - .github/filter.yaml
  - .github/workflows/app-*.yaml
  - apps/**/*
  - packages/**/*
  - tools/**/*
  - package.json
  - turbo.json

api:
  - .github/filter.yaml
  - .github/workflows/api-*.yaml
  - apps/api/**/*
  - packages/**/*
  - tools/**/*
  - package.json
  - turbo.json

web:
  - .github/filter.yaml
  - .github/workflows/website-*.yaml
  - apps/website/**/*
  - packages/**/*
  - tools/**/*
  - package.json
  - turbo.json

catalog:
  - .github/filter.yaml
  - .github/workflows/catalog-*.yaml
  - apps/catalog/**/*
  - apps/website/**/*
  - packages/**/*
  - tools/**/*
  - package.json
  - turbo.json