version: "3.8"
services:
  app:
    image: mona-ca/api:latest
    build:
      context: ../../
      dockerfile: docker/api/Dockerfile
    volumes:
      - type: bind
        source: ../../
        target: /workspaces/mona-ca
      - type: volume
        source: bun-cache
        target: /usr/.bun/install/cache/
    container_name: mona-ca-api
    ports:
      - 3001:3001
    env_file:
      - ../../apps/api/.env
    tty: true

volumes:
  bun-cache: