name: mona-ca-development
services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./docker/data/redis
        target: /data
  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: serverless-redis-http
    ports:
      - 8079:80
    environment:
      SRH_MODE: env
      SRH_TOKEN: SERVERLESS_REDIS_HTTP_TOKEN
      SRH_CONNECTION_STRING: redis://redis:6379
