/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "/Users/kousuke/Desktop/projects/@me/mona-ca/node_modules/@storybook/addon-ondevice-controls/register";
import "/Users/kousuke/Desktop/projects/@me/mona-ca/node_modules/@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "app - mobile",
    directory: "../mobile/src",
    files: "**/*.story.@(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.story\.(ts|tsx))$/,
    // @ts-ignore
    req: require.context(
      '../../mobile/src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.story\.(ts|tsx))$/
    ),
  },
  {
    titlePrefix: "package - ui",
    directory: "../../packages/ui/src",
    files: "**/*.native.story.@(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.story\.(ts|tsx))$/,
    // @ts-ignore
    req: require.context(
      '../../../packages/ui/src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.story\.(ts|tsx))$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();



if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view: View = global.view;
