name="mona-ca"
compatibility_date = "2024-04-19"
main="src/app/index.ts"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "mona-ca_db"
database_id = "b7773705-8f1f-49e2-9a42-564971632cf4"
migrations_dir="drizzle/migrations"