name: API-Deploy-Cloudflare

on:
  push:
    branches:
      - main
  
jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: .github/filters.yaml

  deploy:
    needs: filter
    if: ${{ needs.filter.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      
      - name: Install
        run: bun install --frozen-lockfile

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          command: |
            deploy --env production
            d1 migrations apply mona-ca_db --remote
