name: App-Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: jdx/mise-action@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Test
        run: bun run test
