name: App-Test

on: 
  - push

jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Install
        run: bun install --frozen-lockfile
  
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Format
        run: bun run fmt

  type-check:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Type-Check
        run: bun run type-check
    
  test:
    needs:
      - format
      - lint
      - type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT
  
      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Test
        run: bun run test
    
  build:
    needs:
      - format
      - lint
      - type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-

      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

  status:
    runs-on: ubuntu-latest
    needs: 
      - test
      - build
    if: ${{ ! failure() }}
    steps:
      - name: Check
        run: echo "test is successfully executed."