name: Catalog-Build

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review


jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      catalog: ${{ steps.filter.outputs.catalog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: .github/filters.yaml

  build:
    needs: filter
    if: ${{ needs.filter.outputs.catalog == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Get bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-cache-bun-
      
      - name: Get turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-cache-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-turbo-

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bunx turbo run sb:build
