name: Verify treaty-fetch index.d.ts is committed

on:
  pull_request:
    paths:
      - packages/treaty-fetch/**
      - apps/api/**
      - packages/core/**
      - .github/workflows/treaty-fetch-types-check.yml
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-generated-types:
    name: Check generated types are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build treaty-fetch types
        run: cd packages/treaty-fetch && bun run build:types

      - name: Verify no diff in dist/index.d.ts
        run: |
          git diff --name-only --exit-code -- packages/treaty-fetch/dist/index.d.ts || (
            echo "::error file=packages/treaty-fetch/dist/index.d.ts::Generated types are out of date. Run 'cd packages/treaty-fetch && bun run build:types' and commit changes." &&
            exit 1
          )
